#!/bin/bash


if [ ! -z "$TRAP_ERRORS" ]; then
    trap "$TRAP_ERRORS" ERR
fi


docker-cloud install
lsmod | grep nfs
lsmod | grep nfsd
grep nfs /etc/modules-load.d/nfs.conf
grep nfsd /etc/modules-load.d/nfsd.conf

jq '.experimental' /etc/docker/daemon.json | grep true
jq -r '.["storage-driver"]' /etc/docker/daemon.json | grep overlay2
