#!/bin/bash


if [ ! -z "$TRAP_ERRORS" ]; then
    trap "$TRAP_ERRORS" ERR
fi

# setup grub test
echo "GRUB_TIMEOUT=5" >> /etc/default/grub
echo "echo \"GRUB UPDATED\" > /tmp/grub-update" > /usr/local/bin/update-grub
chmod +x /usr/local/bin/update-grub

# install
docker-cloud install

# nfs modules loaded and configured
lsmod | grep nfs
lsmod | grep nfsd
grep nfs /etc/modules-load.d/nfs.conf
grep nfsd /etc/modules-load.d/nfsd.conf

# ssh ports mangled
grep "^#Port 22" /etc/ssh/sshd_config
grep "^Port 222" /etc/ssh/sshd_config
grep "^Port 333" /etc/ssh/sshd_config
grep "^Port 444" /etc/ssh/sshd_config
grep "^#Port 555" /etc/ssh/sshd_config

# sysfs settings updated
sysctl vm.swappiness | grep 1
sysctl vm.max_map_count | grep 262144
grep vm.swappiness /etc/sysctl.d/fatc.vm.swappiness.conf | grep 1
grep vm.max_map_count /etc/sysctl.d/fatc.vm.max_map_count.conf | grep 262144

# grub timeout
grep "GRUB_TIMEOUT=0" /etc/default/grub
grep "GRUB UPDATED" /tmp/grub-update
