#!/bin/bash


if [ ! -z "$TRAP_ERRORS" ]; then
    trap "$TRAP_ERRORS" ERR
fi


## import the key that the secrets are encrypted with
gpg --allow-secret-key-import --import /tmp/test.key


## unpack secrets
docker-cloud unpack-secrets /tmp/secret/secret-keys.tar.gpg.gz /tmp/unpacked-secrets
grep VERYSECRET /tmp/unpacked-secrets/key1
grep ALSOVERYSECRET /tmp/unpacked-secrets/key2
