#!/bin/bash -e


. /usr/lib/docker-cloud/common


dc_unpack_keys () {
    local tmpdir
    echo "UNPACKING VPN CERTS FROM $1"
    tmpdir=$(mktemp -d)
    cd "$tmpdir"
    zcat "$1" > keys.tar.gpg
    mkdir keys
    gpg --decrypt keys.tar.gpg > keys/keys.tar
    cd keys
    tar xf keys.tar
    rm keys.tar -rf
    ls
    mkdir -p "$2"
    cp -a ./* "$2"
    cd -
    rm -rf "$tmpdir"
}
