#!/bin/bash -e

. /usr/lib/docker-cloud/common


dc_enable_firewall () {
    sed -i 's|[#]*startup=0|startup=1|g' /etc/default/shorewall
    sed -i 's|[#]*DOCKER=No|DOCKER=Yes|g' /etc/shorewall/shorewall.conf
    if systemctl is-system-running; then
	systemctl daemon-reload
	systemctl restart shorewall
    fi
}
