#!/bin/bash -e


. /usr/lib/docker-cloud/common


dc_unpack_secrets () {
    local tmpdir
    tmpdir=$(mktemp -d)
    cwd=$(pwd)
    cd "$tmpdir"
    zcat "$1" > secrets.tar.gpg
    mkdir secrets
    gpg --decrypt secrets.tar.gpg > secrets/secrets.tar
    cd secrets
    tar xf secrets.tar
    rm secrets.tar -rf
    mkdir -p "$2"
    cp -a ./* "$2"
    cd "$cwd"
    rm -rf "$tmpdir"
}
