#!/bin/bash -e

. /usr/lib/docker-cloud/common


SSHD_CONFIG=${SSHD_CONFIG:-/etc/ssh/sshd_config}


dc_set_sysctl () {
    dc_log "Set sysctl: $1 = $2"
    sysctl -w "$1"="$2"
}


dc_set_ssh_ports () {
    local line port

    while read -r line; do
	port=$(echo "$line" | cut -d' ' -f2)
	if ! grep "^${port}$" <<< "${@}" > /dev/null; then
	    dc_log_warn "Disabled port: $port"
	    sed -i "s|^Port ${port}$|#Port ${port}|g" "$SSHD_CONFIG"
	fi
    done < <(grep "^Port" "$SSHD_CONFIG")

    while read -r port; do
	if ! grep "^Port $port" "$SSHD_CONFIG" > /dev/null; then
	    if grep "^#Port $port" "$SSHD_CONFIG" > /dev/null; then
		dc_log "Re-enabled port $port"
		sed -i "s|^#Port ${port}$|Port ${port}|g" "$SSHD_CONFIG"
	    else
		dc_log "Enabled port $port"
		echo "Port ${port}" >> "$SSHD_CONFIG"
	    fi
	else
	    dc_log "Port already enabled $port"
	fi
    done < <(echo "${@}")
}


dc_create_swap () {
    local swapfile swapsize
    swapfile="$1"
    swapsize="$2"
    swapdir=$(dirname "$swapfile")
    if [ ! -d "$swapdir" ];then
	mkdir "$swapdir"
    fi
    if [ -f "$swapfile" ]; then
	dc_log "Swap file already exists"
    else
	fallocate -l "$swapsize" "$swapfile"
	chmod 600 "$swapfile"
	mkswap "$swapfile"
    fi
    if grep -q swap /etc/fstab; then
	dc_log "Swap already configured in fstab"
    else
	echo "$swapfile swap swap defaults 0 0" >> /etc/fstab
    fi
    if grep "$swapfile" /proc/swaps; then
	dc_log_warn "Swap already enabled on $swapfile"
    else
	swapon "$swapfile"
	dc_log "Swap enabled on $swapfile"
    fi
}
