#!/bin/bash -e

. /usr/lib/docker-cloud/common


dc_create_swap () {
    local swapiness swapfile swapsize
    swapfile="$1"
    swapsize="$2"
    swapiness="$3"
    swapdir=$(dirname "$swapfile")
    if [ ! -d "$swapdir" ];then
	mkdir "$swapdir"
    fi
    if [ -f "$swapfile" ]; then
	dc_log "Swap file already exists"
    else
	fallocate -l "$swapsize" "$swapfile"
	chmod 600 "$swapfile"
	mkswap "$swapfile"
    fi
    if grep -q swap /etc/fstab; then
	dc_log "Swap already configured in fstab"
    else
	echo "$swapfile swap swap defaults 0 0" >> /etc/fstab
    fi
    sysctl vm.swappiness="$swapiness"
    swapon "$swapfile"
}
